#!/usr/bin/env bash
set -euox pipefail
cd "$(dirname "$0")"

docker run --rm gcloud gcloud version

docker run --rm gcloud gsutil ls gs://gcp-public-data-landsat

# TODO test our deploy script which we added to the container
