if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

for i in ~/.bash.d/* ; do
  if [ -r "$i" ]; then
    . $i
  fi
done

DOTFILES="$HOME/dev/vorburger-dotfiles-bin-etc"
MYPATH="$DOTFILES/bin:$HOME/.local/bin:$HOME/bin:"
if ! [[ "$PATH" =~ "$MYPATH" ]]
then
    PATH="$MYPATH:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export EDITOR=nano

if hash kubectl 2>/dev/null; then
  source <(kubectl completion bash)
  export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fi
