# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
MYPATH="$HOME/dev/vorburger-dotfiles-bin-etc/bin:$HOME/.local/bin:$HOME/bin:"
if ! [[ "$PATH" =~ "$MYPATH" ]]
then
    PATH="$MYPATH:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export EDITOR=nano
