# from Debian's default .bashrc:
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

for i in ~/.bash.d/* ; do
  if [ -x "$i" ]; then
    . $i
  fi
done

# kept as in original Fedora /etc/skel/.bashrc (additional PATHs should go into dotfiles/bash.d & ~/.bash.d)
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=


# User specific aliases and functions should go into dotfiles/bash.d/ instead of being appended here!

# Do *NOT* set 'SSH_AUTH_SOCK' here; see README for details.

# added by travis gem
# [ ! -s $HOME/.travis/travis.sh ] || source $HOME/.travis/travis.sh
[ -s $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

[ -s /usr/bin/kitty ] && source <(kitty + complete setup bash)

[ -s /usr/bin/gh ] && eval "$(gh completion -s bash)"

# NB: "chsh -s /bin/fish" doesn't work (for some unclear reason), but this works, from:
# https://wiki.archlinux.org/index.php/Fish#Modify_.bashrc_to_drop_into_fish
# NO!!! https://bugzilla.redhat.com/show_bug.cgi?id=1910424
# [ -s /usr/bin/fish ] && [[ $(ps --no-header --pid=$PPID --format=cmd) != "fish" ]] && exec fish

# from Debian's default .bashrc:
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

[ -s "$HOME/.web3j/source.sh" ] && source "$HOME/.web3j/source.sh"

# https://buildpacks.io/docs/app-developer-guide/building-on-podman/
if command -v podman >/dev/null 2>&1; then
  export DOCKER_HOST="unix://$(podman info -f "{{.Host.RemoteSocket.Path}}")"
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# For https://rustup.rs
[ -f ~/.cargo/env ] && source ~/.cargo/env
