# https://starship.rs/config/

# This does NOT avoid line break in the prompt; see https://github.com/starship/starship/issues/1987
# add_newline = false

# https://starship.rs/config/#prompt
# Move Kubernetes to end instead of start as per default
# format="$all$kubernetes$cmd_duration$character"

[line_break]
disabled = true

[directory]
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1
[directory.substitutions]
'vorburger-dotfiles-bin-etc' = 'v…d'

[java]
# drop Java version from prompt; format default = "via [${symbol}${version}]($style) "
format = "via [${symbol}]($style)"
style = "bold blue"
# symbol = " " # cute, but too faint

[username]
format = "[$user]($style) on "  # use 'on' instead of default 'in'
disabled = true
# Disabled because otherwise it's always shown in the dotfiles container
# (because we use it via SSH) and is more in the way than particularly useful,
# at least in Starship v1.10.3.

[hostname]
# disabled = true
# same reason as for username, see above

[cmd_duration]
show_notifications = true
# https://github.com/starship/starship/issues/1933 (TL;DR it's annoying to get/see this for every $EDITOR use)
disabled = true

[gcloud]
style = "dimmed blue"
# drop stuff for shorter prompt; default https://starship.rs/config/#google-cloud-gcloud
format = '[$symbol(\($region\))]($style)'
[gcloud.project_aliases]
"vorburger-learn-appengin" = "learn"

[kubernetes]
disabled = true
[kubernetes.context_aliases]
"gke_oasis-learn-study_europe-west4_cluster1" = "oasis"

[git_metrics]
disabled = false

[status]
disabled = false

[sudo]
disabled = true
# This doesn't appear to work within containers (at least in Starship v1.10.3),
# and is always shown, even if no sudo was done, and even after "sudo -K" drops it.
# Or perhaps it's not container related but because the dotfiles devshell container
# has /etc/sudoers with NOPASSWD for %wheel.   Same in GitHub Codespaces as well.
# Either way - it's ugly / in the way and useless if it's always shown.

[[battery.display]]
threshold = 50

[docker_context]
disabled = true

[container]
disabled = true

[ruby]
# RUBY_VERSION is *always* set in GitHub Codespaces, so it adds no value
detect_variables=["RBENV_VERSION"]

[python]
# I like the cute yellow duck but don't need to always see the version everywhere
version_format = ''
