#!/usr/bin/env bash
set -euox pipefail
cd "$(dirname "$0")"

# TODO this should be changed to test SSH from one container, with an agent, into another..
# currently that is not what this tests: instead it's testing SSH from where this runs into a container, with an agent.

# Test that the local SSH Agent works (on the laptop/build server, where this script runs; NOT in container)
SSH_AUTH_SOCK=${SSH_AUTH_SOCK:-default_value}
if [[ -z "$SSH_AUTH_SOCK" || "$SSH_AUTH_SOCK" == "default_value" ]]; then
  echo "Starting SSH Agent..."
  eval "$(ssh-agent -s)"
fi

# TODO instead of copy/paste from ../sshd/test, share common test harness structure..

docker rm --force test-"$1" || true
docker run -d -p 2222 --name test-"$1" "$1"
PORT="$(docker port test-"$1" | head -n1 | sed 's/2222\/tcp -> 0.0.0.0://')"
sleep 2

rm -f /tmp/test-$$-id_rsa*
ssh-keygen -f /tmp/test-$$-id_rsa -P "" -C test
ssh-add /tmp/test-$$-id_rsa
docker exec test-"$1" /usr/local/sbin/add-uid-key tester /bin/bash "$(cat /tmp/test-$$-id_rsa.pub)"

# NB -A for Agent Forwarding!
ssh -A -i /tmp/test-$$-id_rsa -o "StrictHostKeyChecking=no" -p "$PORT" tester@localhost ssh-add -l

# TODO fire up another sshd container, and "cross hop" into it by agent forwarding

docker rm --force test-"$1"

echo Test successful.
