steps:

# Google Cloud Shell Custom Images are ephemeral and cannot be made persistent, so this is a bit pointless; see README
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.']
#- name: 'gcr.io/cloudshell-images/custom-image-validation'
#  args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME']
#images: ['gcr.io/$PROJECT_ID/$REPO_NAME']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['container/build.sh']
  # TODO script must tag the dotfiles-fedora image as gcr.io/$PROJECT_ID/dotfiles-fedora?
images: ['gcr.io/$PROJECT_ID/dotfiles-fedora']

timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_32'
# machineType default is e2-medium with 1 vCPU and 4 GB memory, see https://cloud.google.com/build/pricing
