FROM devshell
# see ./container/devshell

COPY dnf-install.sh /tmp/
RUN /tmp/dnf-install.sh

ADD https://www.vorburger.ch/gpg/ssh-authorized_keys /tmp/vorburger.ch_keys
ADD https://github.com/vorburger.keys /tmp/vorburger_github_keys
RUN /usr/local/sbin/add-uid-key vorburger "$(cat /tmp/vorburger.ch_keys /tmp/vorburger_github_keys)"

USER vorburger
WORKDIR /home/vorburger/
RUN mkdir -p dev/vorburger-dotfiles-bin-etc

# Do NOT do this, because then any time you touch any file during dev, it will redo above:
#   COPY . /home/vorburger/dev/vorburger-dotfiles-bin-etc/
COPY --chown=vorburger:vorburger symlink.sh /home/vorburger/dev/vorburger-dotfiles-bin-etc/
COPY --chown=vorburger:vorburger dotfiles/  /home/vorburger/dev/vorburger-dotfiles-bin-etc/dotfiles/
COPY --chown=vorburger:vorburger bin/       /home/vorburger/dev/vorburger-dotfiles-bin-etc/bin/

# as per ./README.md
RUN cd /home/vorburger/dev/ && git clone https://github.com/scopatz/nanorc.git && cd .. \
 && rm /home/vorburger/.bashrc \
 && /home/vorburger/dev/vorburger-dotfiles-bin-etc/symlink.sh

# see docs/podman.md
RUN sudo dnf install -y podman-remote

# We have to reset the user to root so that sshd (FROM parent images) will start (as intended)
USER root
WORKDIR /
