# This is a "minimal" variant of ./Dockerfile-debian that is only used for testing during fast iterative development.
# Remember to update SUSE repository when upgrading :bullseye
FROM debian:bullseye

RUN apt-get update && apt install -y curl gpg
RUN echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' | tee /etc/apt/sources.list.d/shells:fish:release:3.list
RUN curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null

RUN apt-get update && apt install -y fish git

COPY *.sh /var/local/vorburger-dotfiles/
COPY dotfiles /var/local/vorburger-dotfiles/dotfiles/

RUN /var/local/vorburger-dotfiles/symlink-homefree.sh

# COPY etc/profile.d/* /var/local/vorburger-dotfiles/etc/profile.d/
# RUN echo "hello, world from /etc/profile" >>/etc/profile

ENTRYPOINT fish
