FROM registry.fedoraproject.org/fedora-toolbox:34
RUN sudo dnf update -y

# Nota bene that the ~ home directory has to remain empty
# in a toolbox container (because the host's is mounted)

COPY dnf-install.sh /tmp/
RUN /tmp/dnf-install.sh

RUN curl https://krypt.co/kr | sh

COPY dotfiles/.nanorc /etc/nanorc.dotfiles
RUN cp /etc/nanorc /etc/nanorc.original && \
    cp /etc/nanorc.dotfiles /etc/nanorc && \
    sed -i 's!~/dev/nanorc!/usr/share/nano-scopatz!g' /etc/nanorc && \
    git clone https://github.com/scopatz/nanorc.git /usr/share/nano-scopatz && \
    grep -v "#" /etc/nanorc.original | uniq >>/etc/nanorc

COPY dotfiles/gitconfig /etc/gitconfig

COPY bin/findx /usr/local/bin/
COPY bin/g*    /usr/local/bin/
