# Remember to update SUSE repository in ./apt-install.sh when upgrading :bullseye
FROM debian:bullseye

# The debian container doesn't come with sudo, so for apt-install.sh which uses sudo to work as everywhere else we install it:
RUN apt-get update
RUN apt install sudo

COPY . /var/local/vorburger-dotfiles/

RUN /var/local/vorburger-dotfiles/apt-install.sh
RUN /var/local/vorburger-dotfiles/symlink-homefree.sh

ENTRYPOINT fish
