# Dockerfile-fedora WITHOUT ssh (which isn't really all that useful, actually)
FROM fedora:35

RUN dnf update -y

COPY dnf-install.sh /tmp/
RUN /tmp/dnf-install.sh

RUN useradd vorburger
WORKDIR /home/vorburger/
USER vorburger

# Do NOT do this, because then any time you touch any file during dev, it will redo above:
#   COPY . /home/vorburger/dev/vorburger-dotfiles-bin-etc/
COPY --chown=vorburger:vorburger symlink.sh /home/vorburger/dev/vorburger-dotfiles-bin-etc/
COPY --chown=vorburger:vorburger dotfiles/  /home/vorburger/dev/vorburger-dotfiles-bin-etc/dotfiles/
COPY --chown=vorburger:vorburger bin/       /home/vorburger/dev/vorburger-dotfiles-bin-etc/bin/

# as per ./README.md
RUN cd /home/vorburger/dev/ && git clone https://github.com/scopatz/nanorc.git && cd .. \
 && rm /home/vorburger/.bashrc \
 && /home/vorburger/dev/vorburger-dotfiles-bin-etc/symlink.sh
