#!/usr/bin/env bash
set -euox pipefail

NEW_UID=$1
AUTHORIZED_KEYS=$2

useradd "$NEW_UID"
mkdir /home/"$NEW_UID"/.ssh/
echo "$AUTHORIZED_KEYS" > /home/"$NEW_UID"/.ssh/authorized_keys
chown -R "$NEW_UID":"$NEW_UID" /home/"$NEW_UID"/.ssh
chmod 700 /home/"$NEW_UID"/.ssh
