# https://github.com/NixOS/nix/issues/11728
# NO NEED ANYMORE! download-buffer-size = 1048576000

# Accept the flake configuration automatically
accept-flake-config = true

# Or explicitly add the substituter and its public key
extra-substituters = https://cache.numtide.com
extra-trusted-public-keys = niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=
