[[rule]]
decision = "allow"
priority = 950
toolName = "enter_plan_mode"

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [
  "find",
  "grep",
  "sed",
  "[",
  "basename",
  "date",
  "dirname",
  "cut",
  "echo",
  "cat",
  "mv"
]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "mkdir", "nix" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "ls", "head", "grep" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "head", "od" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "hugo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "ls" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "which" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "./symlink.sh" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "git" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "replace"
argsPattern = '\\0\"file_path\":\"flake\.nix\"\\0'
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "activate_skill"
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "wait" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "ps" ]
modes = [ "autoEdit", "yolo" ]
