[[rule]]
decision = "allow"
priority = 950
toolName = "enter_plan_mode"

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [
  "find",
  "grep",
  "sed",
  "[",
  "basename",
  "date",
  "dirname",
  "cut",
  "echo",
  "cat",
  "mv"
]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "mkdir", "nix" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "ls", "head", "grep" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "head", "od" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "hugo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "ls" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "which" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "./symlink.sh" ]

[[rule]]
decision = "allow"
priority = 950
mcpName = "nix"
toolName = "mcp_nix_nix"

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "nix-build", "find", "head" ]
