#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: $0 <project> <current version> <target version>"
    echo "E.g. $0 odlparent 3.0.2 3.1.0-SNAPSHOT"
    exit 1
fi

project=$1
curver=$2
target=$3

for file in $(find . -type f -name \*.xml | xargs grep -l ${curver})
do
    echo -n Processing ${file}...
    xmlstarlet ed -P -N mvn=http://maven.apache.org/POM/4.0.0 -u //mvn:version[../mvn:groupId=\"org.opendaylight.${project}\"] -v ${target} ${file} > ${file}.new
    mv ${file}.new ${file}
    echo " done."
done
