# Use the system daemon instead of internal drivers
disable-ccid
pcsc-shared

# Release the card quickly to prevent "ghost" locks
card-timeout 1

# Explicitly point to the (64-bit) library, if needed (but it's not)
#pcsc-driver /usr/lib64/libpcsclite.so.1
